### ISSUE TITLE
Keep Same Link

### ISSUE THREAD

**Issue by Allui** [getappbox/fastlane-plugin-appbox#1]
Can i set "keepsamelink" argument?
I tried to run AppBox like that:
```ruby
exit_status = system("exec #{$appbox_path} ipa='../#{$output_beta_full_path}' email='#{$testers} keepsamelink=true")
```

But it didn't work... It generated a new link

**Comment by vineetchoudhary** [comment]
Hi, thanks for the bug report. I'm working on a fix.

**Comment by vineetchoudhary** [comment]
Hi, I've fixed the issue. In order to use, please download [AppBox v2.7.2](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases) and [AppBox Fastlane plugin v1.1.0](https://github.com/getappbox/fastlane-plugin-appbox/releases). 

Here the demo lane for keep same link - 

```rb
default_platform(:ios)

platform :ios do
  lane :gymbox do
    gym
    appbox(
        emails: 'you@example.com',
        message: '{PROJECT_NAME} - {BUILD_VERSION}({BUILD_NUMBER}) is ready to test.',
        keep_same_link: true,
    )
  end
end
```
