### ISSUE TITLE
Failed to open Zip File

### ISSUE THREAD

**Issue by SK-sep** [getappbox/fastlane-plugin-appbox#10]
<img width="807" alt="CleanShot 2022-10-17 at 21 56 36@2x" src="https://user-images.githubusercontent.com/34976610/196211195-4cc44368-4504-45ba-995a-8dd236fc6e74.png">

AppBox Showing popup 'Failed to open zip file' like this
Any information about this issue ?

Thanks before

**Comment by SK-sep** [comment]
<img width="396" alt="CleanShot 2022-10-18 at 01 59 01@2x" src="https://user-images.githubusercontent.com/34976610/196260026-7aebba17-8b59-4b4b-a373-7e9fa5c9c5e0.png">

Solve
Downgrade it to version 2.9.6

**Comment by aendel** [comment]
+1 
With version: Version 3.2.0 (1)
