### ISSUE TITLE
Get appbox link in SharedValues

### ISSUE THREAD

**Issue by vin-the-dev** [getappbox/fastlane-plugin-appbox#3]
Can you make the shareable link accessible via SharedValues in lane?

Just a quick question not related the issue. Can we use google drive for uploading iOS builds. I am stuck at making the link sharable of manifest file. Any pointers will be great. Thanks for this great project.

**Comment by vineetchoudhary** [comment]
> Can you make the shareable link accessible via SharedValues in lane?

Yes, I can do that. Just need to execute `export` command from AppBox macOS application. I'll add that in next release.

> Google Drive 

I've tried too many options but some of them doesn't provide the direct download link and some of them doesn't have proper SDK. Here the more details about the same - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/82

**Comment by vin-the-dev** [comment]
Thank you @vineetchoudhary  seems, google drive is out of the scope. I am doing react native, we primarily use google drive. I will have to find a way to use android app to upload to dropbox. All good bro let me know when next version releases.

**Comment by vineetchoudhary** [comment]
Sure. I've added in AppBox fastlane plugin https://github.com/getappbox/fastlane-plugin-appbox/commit/fe7160bacb6287481e02467f02e6a40ed9aab2f0. But need to add the same in AppBox macOS Application. I hope `NSTask` supports shell builtin command.

**Comment by vineetchoudhary** [comment]
**Update:**
Seems like `NSTask` doesn't support shell builtin command(`export`). I've tried multiple approaches to use `export` command (https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/commit/65a22a67ea35696486f2910db8c3a0ea826c6026,  https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/commit/26ab6b7b7b56f8c65291b8ce001b99216b13bc5b), but nothing works. Now I've to use something different from `export` command, which can share information between AppBox macOS application and Fastlane plugin.

**Comment by vineetchoudhary** [comment]
Released with version 1.4.0 and AppBox version 2.8.0.

https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases
