### ISSUE TITLE
How to include QR code in email

### ISSUE THREAD

**Issue by shahidlatif2007** [getappbox/fastlane-plugin-appbox#5]
HI,

There is no option of adding QR code in email.

**Comment by vineetchoudhary** [comment]
Hi @shahidlatif2007 ,

Currently, there is no way to include QR code in an email. However, you can open the installation link and there is a "Show QR Code" option.

**Comment by shahidlatif2007** [comment]
Hi @vineetchoudhary ,

Thanks for reply.

OK. Can you tell me why it is not added?

**Comment by vineetchoudhary** [comment]
At that time, I thought, one place is enough for QR code.

**Comment by shahidlatif2007** [comment]
HI @vineetchoudhary ,

I think it very good to have that option. Sometime If I send build to other guys using email and that email has not been configure on device then he has to type the link. Please add this in your to do list if you can.
