### ISSUE TITLE
[Question] How to only upload ipa file existed?

### ISSUE THREAD

**Issue by anhhtbk** [getappbox/fastlane-plugin-appbox#6]
I can export IPA file with Fastlane, but can't with gym appbox. So I want to only upload this IPA file by appbox.

**Comment by vineetchoudhary** [comment]
Hi, I need a little bit more information on this. 
- Did you have installed the latest [AppBox macOS application](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation) in your mac? 
- If yes, do you've your dropbox account logged in that application?
- If yes, please share your Fastflie?

**Comment by anhhtchy** [comment]
@vineetchoudhary Thanks for your response. I did export the IPA file by appbox. But I don't know how to select the default scheme or disable upload AppStore. You can show all the available variables?
